# Generated by Django 3.0.7 on 2020-08-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('fname', models.CharField(max_length=25)),
                ('lname', models.CharField(max_length=25)),
                ('uname', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('psw', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='adminl',
            name='admin_id',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
